#!/bin/bash
#My Bash lab 3

#use the which command to see if we have lxd on the system already
echo "Step1. Installing LXD in the vm"
which lxd >/dev/null
if [ $? -ne 0 ]; then
	# need to install lxd
	echo "Installing lxd - you may have to enter your password to install it"
	sudo snap install lxd
	if [ $? -ne 0 ]; then
	#failed to install lxd - exit with an error message and status
		echo "Failed to install lxd software which is require."
		exit 1
	fi
else
echo "---------"
echo "Output = lxd is already installed in the vm"
fi

echo "----------"
echo "----------"

echo "Step2. Running lxbr0 in the vm"
echo "----------"
#running lxbr0 in the vm using lxd init --auto
ip a | grep -w "lxdbr0" > /dev/null

if [ $? -ne 0 ]; then
	lxd init --auto
	echo "Output=lxdbr0 is created" 
fi
