#!/bin/bash
#My Bash lab 3

echo "Step1. Installing LXD in the VM"
echo "----------"
#checking if lxd is installed or not. I had used which lxd command to find this location 

if [ -e "/snap/bin/lxd" ]; then
    echo "Output = lxd is already installed in the VM"
else
    "$(sudo snap install lxd)"
        echo "lxd installed successfully"
fi
echo "----------"
echo "----------"

echo "Step2. Running lxbr0 in the vm"
echo "----------"
#running lxbr0 in the vm using lxd init --auto
$(lxd init --auto)
echo "Output = lxbr0 is created"

